// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BLL.Models;

public partial class Student
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public DateTime? BirthDate { get; set; }

    public decimal? GPA { get; set; }
}